'use client';

// This file is automatically generated. Do not modify it manually.
import { FirebaseOptions, initializeApp, getApp, getApps } from 'firebase/app';

const firebaseConfig: FirebaseOptions = {
  projectId: 'studio-7888215262-30e03',
  appId: '1:997550181359:web:93a21133ab4605e4eac41a',
  apiKey: 'AIzaSyB-XJ5L9QCbav29OGvOxDRkbCEa8gQOAJo',
  authDomain: 'studio-7888215262-30e03.firebaseapp.com',
  measurementId: '',
  messagingSenderId: '997550181359',
};

function createFirebaseApp(config: FirebaseOptions) {
  if (!getApps().length) {
    return initializeApp(config);
  }
  return getApp();
}

export const firebaseApp = createFirebaseApp(firebaseConfig);
